name = "MemorylessNonlinearities"
uuid = "0fdea88e-d355-4a76-8041-e2244589d5bd"
authors = ["Too Yuen Min"]
version = "0.1.1"

[deps]
AlphaStableDistributions = "f20549b4-2d50-407f-863c-cdd202ba59a3"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
AlphaStableDistributions = "1.1"
DelimitedFiles = "1"
Interpolations = "0.12, 0.13, 0.14"
QuadGK = "2.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
