name = "MemorylessNonlinearities"
uuid = "0fdea88e-d355-4a76-8041-e2244589d5bd"
authors = ["Too Yuen Min"]
version = "0.1.0"

[deps]
AlphaStableDistributions = "f20549b4-2d50-407f-863c-cdd202ba59a3"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
AlphaStableDistributions = "1.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
